// Code generated by protoc-gen-go. DO NOT EDIT.
// source: erepro/api/auth/v1/auth.proto

package auth // import "github.com/erepro-apis/erepro/api/auth/v1"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_516f9db3dbbd1557, []int{0}
}
func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (dst *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(dst, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthResponse struct {
	Authenticated        bool     `protobuf:"varint,1,opt,name=authenticated" json:"authenticated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_516f9db3dbbd1557, []int{1}
}
func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (dst *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(dst, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetAuthenticated() bool {
	if m != nil {
		return m.Authenticated
	}
	return false
}

func init() {
	proto.RegisterType((*AuthRequest)(nil), "erego.api.auth.v1.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "erego.api.auth.v1.AuthResponse")
}

func init() { proto.RegisterFile("erepro/api/auth/v1/auth.proto", fileDescriptor_auth_516f9db3dbbd1557) }

var fileDescriptor_auth_516f9db3dbbd1557 = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xcf, 0x4a, 0xc4, 0x30,
	0x10, 0x87, 0xe9, 0x22, 0x52, 0xa3, 0x7b, 0x30, 0x5e, 0x96, 0xe2, 0x3f, 0x8a, 0x07, 0x11, 0x4c,
	0x5c, 0xf5, 0xa4, 0x27, 0x05, 0x5f, 0xa0, 0x47, 0x6f, 0xd9, 0xed, 0xd0, 0x06, 0x76, 0x33, 0x31,
	0x33, 0x59, 0xef, 0xbe, 0x82, 0x8f, 0xe6, 0x2b, 0xf8, 0x20, 0xd2, 0x86, 0x8a, 0x52, 0xf6, 0x34,
	0xcc, 0xfc, 0xf8, 0x66, 0x92, 0x4f, 0x9c, 0x40, 0x00, 0x1f, 0x50, 0x1b, 0x6f, 0xb5, 0x89, 0xdc,
	0xea, 0xcd, 0xbc, 0xaf, 0xca, 0x07, 0x64, 0x94, 0x87, 0x10, 0xa0, 0x41, 0x65, 0xbc, 0x55, 0xfd,
	0x74, 0x33, 0x2f, 0x8e, 0x1b, 0xc4, 0x66, 0x05, 0x89, 0x70, 0x0e, 0xd9, 0xb0, 0x45, 0x47, 0x09,
	0x28, 0x5f, 0xc4, 0xfe, 0x53, 0xe4, 0xb6, 0x82, 0xb7, 0x08, 0xc4, 0xb2, 0x10, 0x79, 0x24, 0x08,
	0xce, 0xac, 0x61, 0x96, 0x9d, 0x67, 0x97, 0x7b, 0xd5, 0x6f, 0xdf, 0x65, 0xde, 0x10, 0xbd, 0x63,
	0xa8, 0x67, 0x93, 0x94, 0x0d, 0x7d, 0x79, 0x2f, 0x0e, 0xd2, 0x1a, 0xf2, 0xe8, 0x08, 0xe4, 0x85,
	0x98, 0x76, 0xf7, 0xc1, 0xb1, 0x5d, 0x1a, 0x86, 0xba, 0x5f, 0x96, 0x57, 0xff, 0x87, 0xb7, 0x2b,
	0xb1, 0xd3, 0x51, 0xb2, 0x4e, 0xf4, 0x10, 0xc8, 0x53, 0x35, 0xfa, 0x86, 0xfa, 0xf3, 0xca, 0xe2,
	0x6c, 0x6b, 0x9e, 0xce, 0x97, 0x47, 0x1f, 0x5f, 0xdf, 0x9f, 0x93, 0x69, 0x99, 0x0f, 0x7a, 0x1e,
	0xb2, 0xab, 0xe7, 0x9b, 0x57, 0xd5, 0x58, 0x6e, 0xe3, 0x42, 0x2d, 0x71, 0xad, 0x93, 0xc7, 0x6b,
	0xe3, 0x2d, 0xe9, 0xb1, 0xd3, 0xc7, 0xae, 0x2e, 0x76, 0x7b, 0x47, 0x77, 0x3f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xc9, 0x0c, 0xdf, 0x0d, 0x75, 0x01, 0x00, 0x00,
}
