# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from erepro.api.auth.v1 import auth_pb2 as erepro_dot_api_dot_auth_dot_v1_dot_auth__pb2


class AuthStub(object):
  """Auth is responsible for the user authentication
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Authenticate = channel.unary_unary(
        '/erego.api.auth.v1.Auth/Authenticate',
        request_serializer=erepro_dot_api_dot_auth_dot_v1_dot_auth__pb2.AuthRequest.SerializeToString,
        response_deserializer=erepro_dot_api_dot_auth_dot_v1_dot_auth__pb2.AuthResponse.FromString,
        )


class AuthServicer(object):
  """Auth is responsible for the user authentication
  """

  def Authenticate(self, request, context):
    """Authenticate
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AuthServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Authenticate': grpc.unary_unary_rpc_method_handler(
          servicer.Authenticate,
          request_deserializer=erepro_dot_api_dot_auth_dot_v1_dot_auth__pb2.AuthRequest.FromString,
          response_serializer=erepro_dot_api_dot_auth_dot_v1_dot_auth__pb2.AuthResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'erego.api.auth.v1.Auth', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
