// Code generated by protoc-gen-go. DO NOT EDIT.
// source: erepro/api/branches/v1/branches.proto

package erepro_api_branches_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "google.golang.org/genproto/googleapis/longrunning"
import field_mask "google.golang.org/genproto/protobuf/field_mask"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BrancheOperation_OperationType int32

const (
	BrancheOperation_OPERATION_TYPE_UNSPECIFIED BrancheOperation_OperationType = 0
	BrancheOperation_CREATE                     BrancheOperation_OperationType = 1
)

var BrancheOperation_OperationType_name = map[int32]string{
	0: "OPERATION_TYPE_UNSPECIFIED",
	1: "CREATE",
}
var BrancheOperation_OperationType_value = map[string]int32{
	"OPERATION_TYPE_UNSPECIFIED": 0,
	"CREATE":                     1,
}

func (x BrancheOperation_OperationType) String() string {
	return proto.EnumName(BrancheOperation_OperationType_name, int32(x))
}
func (BrancheOperation_OperationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_branches_bed202e6cba05c9f, []int{9, 0}
}

type Branch struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	DisplayName          string               `protobuf:"bytes,2,opt,name=display_name,json=displayName" json:"display_name,omitempty"`
	Address              string               `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
	NoBeds               uint32               `protobuf:"varint,4,opt,name=no_beds,json=noBeds" json:"no_beds,omitempty"`
	NoBaths              uint32               `protobuf:"varint,5,opt,name=no_baths,json=noBaths" json:"no_baths,omitempty"`
	Price                uint64               `protobuf:"varint,6,opt,name=price" json:"price,omitempty"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,7,opt,name=create_time,json=createTime" json:"create_time,omitempty"`
	UpdateTime           *timestamp.Timestamp `protobuf:"bytes,8,opt,name=update_time,json=updateTime" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Branch) Reset()         { *m = Branch{} }
func (m *Branch) String() string { return proto.CompactTextString(m) }
func (*Branch) ProtoMessage()    {}
func (*Branch) Descriptor() ([]byte, []int) {
	return fileDescriptor_branches_bed202e6cba05c9f, []int{0}
}
func (m *Branch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Branch.Unmarshal(m, b)
}
func (m *Branch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Branch.Marshal(b, m, deterministic)
}
func (dst *Branch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Branch.Merge(dst, src)
}
func (m *Branch) XXX_Size() int {
	return xxx_messageInfo_Branch.Size(m)
}
func (m *Branch) XXX_DiscardUnknown() {
	xxx_messageInfo_Branch.DiscardUnknown(m)
}

var xxx_messageInfo_Branch proto.InternalMessageInfo

func (m *Branch) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Branch) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Branch) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Branch) GetNoBeds() uint32 {
	if m != nil {
		return m.NoBeds
	}
	return 0
}

func (m *Branch) GetNoBaths() uint32 {
	if m != nil {
		return m.NoBaths
	}
	return 0
}

func (m *Branch) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Branch) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *Branch) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

type ListBranchesRequest struct {
	PageSize             int32    `protobuf:"varint,1,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	PageToken            string   `protobuf:"bytes,2,opt,name=page_token,json=pageToken" json:"page_token,omitempty"`
	ShowDelete           bool     `protobuf:"varint,3,opt,name=show_delete,json=showDelete" json:"show_delete,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBranchesRequest) Reset()         { *m = ListBranchesRequest{} }
func (m *ListBranchesRequest) String() string { return proto.CompactTextString(m) }
func (*ListBranchesRequest) ProtoMessage()    {}
func (*ListBranchesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_branches_bed202e6cba05c9f, []int{1}
}
func (m *ListBranchesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBranchesRequest.Unmarshal(m, b)
}
func (m *ListBranchesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBranchesRequest.Marshal(b, m, deterministic)
}
func (dst *ListBranchesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBranchesRequest.Merge(dst, src)
}
func (m *ListBranchesRequest) XXX_Size() int {
	return xxx_messageInfo_ListBranchesRequest.Size(m)
}
func (m *ListBranchesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBranchesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListBranchesRequest proto.InternalMessageInfo

func (m *ListBranchesRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListBranchesRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

func (m *ListBranchesRequest) GetShowDelete() bool {
	if m != nil {
		return m.ShowDelete
	}
	return false
}

type ListBranchesResponse struct {
	Branches             []*Branch `protobuf:"bytes,1,rep,name=branches" json:"branches,omitempty"`
	NextPageToken        string    `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListBranchesResponse) Reset()         { *m = ListBranchesResponse{} }
func (m *ListBranchesResponse) String() string { return proto.CompactTextString(m) }
func (*ListBranchesResponse) ProtoMessage()    {}
func (*ListBranchesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_branches_bed202e6cba05c9f, []int{2}
}
func (m *ListBranchesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBranchesResponse.Unmarshal(m, b)
}
func (m *ListBranchesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBranchesResponse.Marshal(b, m, deterministic)
}
func (dst *ListBranchesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBranchesResponse.Merge(dst, src)
}
func (m *ListBranchesResponse) XXX_Size() int {
	return xxx_messageInfo_ListBranchesResponse.Size(m)
}
func (m *ListBranchesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBranchesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBranchesResponse proto.InternalMessageInfo

func (m *ListBranchesResponse) GetBranches() []*Branch {
	if m != nil {
		return m.Branches
	}
	return nil
}

func (m *ListBranchesResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type SearchBranchesRequest struct {
	PageSize             int32    `protobuf:"varint,1,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	PageToken            string   `protobuf:"bytes,2,opt,name=page_token,json=pageToken" json:"page_token,omitempty"`
	Query                string   `protobuf:"bytes,3,opt,name=query" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchBranchesRequest) Reset()         { *m = SearchBranchesRequest{} }
func (m *SearchBranchesRequest) String() string { return proto.CompactTextString(m) }
func (*SearchBranchesRequest) ProtoMessage()    {}
func (*SearchBranchesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_branches_bed202e6cba05c9f, []int{3}
}
func (m *SearchBranchesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchBranchesRequest.Unmarshal(m, b)
}
func (m *SearchBranchesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchBranchesRequest.Marshal(b, m, deterministic)
}
func (dst *SearchBranchesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchBranchesRequest.Merge(dst, src)
}
func (m *SearchBranchesRequest) XXX_Size() int {
	return xxx_messageInfo_SearchBranchesRequest.Size(m)
}
func (m *SearchBranchesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchBranchesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchBranchesRequest proto.InternalMessageInfo

func (m *SearchBranchesRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *SearchBranchesRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

func (m *SearchBranchesRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type SearchBranchesResponse struct {
	Branches             []*Branch `protobuf:"bytes,1,rep,name=branches" json:"branches,omitempty"`
	NextPageToken        string    `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SearchBranchesResponse) Reset()         { *m = SearchBranchesResponse{} }
func (m *SearchBranchesResponse) String() string { return proto.CompactTextString(m) }
func (*SearchBranchesResponse) ProtoMessage()    {}
func (*SearchBranchesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_branches_bed202e6cba05c9f, []int{4}
}
func (m *SearchBranchesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchBranchesResponse.Unmarshal(m, b)
}
func (m *SearchBranchesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchBranchesResponse.Marshal(b, m, deterministic)
}
func (dst *SearchBranchesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchBranchesResponse.Merge(dst, src)
}
func (m *SearchBranchesResponse) XXX_Size() int {
	return xxx_messageInfo_SearchBranchesResponse.Size(m)
}
func (m *SearchBranchesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchBranchesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchBranchesResponse proto.InternalMessageInfo

func (m *SearchBranchesResponse) GetBranches() []*Branch {
	if m != nil {
		return m.Branches
	}
	return nil
}

func (m *SearchBranchesResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type GetBranchRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBranchRequest) Reset()         { *m = GetBranchRequest{} }
func (m *GetBranchRequest) String() string { return proto.CompactTextString(m) }
func (*GetBranchRequest) ProtoMessage()    {}
func (*GetBranchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_branches_bed202e6cba05c9f, []int{5}
}
func (m *GetBranchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBranchRequest.Unmarshal(m, b)
}
func (m *GetBranchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBranchRequest.Marshal(b, m, deterministic)
}
func (dst *GetBranchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBranchRequest.Merge(dst, src)
}
func (m *GetBranchRequest) XXX_Size() int {
	return xxx_messageInfo_GetBranchRequest.Size(m)
}
func (m *GetBranchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBranchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBranchRequest proto.InternalMessageInfo

func (m *GetBranchRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateBranchRequest struct {
	Branch               *Branch  `protobuf:"bytes,1,opt,name=branch" json:"branch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBranchRequest) Reset()         { *m = CreateBranchRequest{} }
func (m *CreateBranchRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBranchRequest) ProtoMessage()    {}
func (*CreateBranchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_branches_bed202e6cba05c9f, []int{6}
}
func (m *CreateBranchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBranchRequest.Unmarshal(m, b)
}
func (m *CreateBranchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBranchRequest.Marshal(b, m, deterministic)
}
func (dst *CreateBranchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBranchRequest.Merge(dst, src)
}
func (m *CreateBranchRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBranchRequest.Size(m)
}
func (m *CreateBranchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBranchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBranchRequest proto.InternalMessageInfo

func (m *CreateBranchRequest) GetBranch() *Branch {
	if m != nil {
		return m.Branch
	}
	return nil
}

type UpdateBranchRequest struct {
	Branch               *Branch               `protobuf:"bytes,1,opt,name=branch" json:"branch,omitempty"`
	UpdateMask           *field_mask.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateBranchRequest) Reset()         { *m = UpdateBranchRequest{} }
func (m *UpdateBranchRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateBranchRequest) ProtoMessage()    {}
func (*UpdateBranchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_branches_bed202e6cba05c9f, []int{7}
}
func (m *UpdateBranchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBranchRequest.Unmarshal(m, b)
}
func (m *UpdateBranchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBranchRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateBranchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBranchRequest.Merge(dst, src)
}
func (m *UpdateBranchRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateBranchRequest.Size(m)
}
func (m *UpdateBranchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBranchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBranchRequest proto.InternalMessageInfo

func (m *UpdateBranchRequest) GetBranch() *Branch {
	if m != nil {
		return m.Branch
	}
	return nil
}

func (m *UpdateBranchRequest) GetUpdateMask() *field_mask.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

type DeleteBranchRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBranchRequest) Reset()         { *m = DeleteBranchRequest{} }
func (m *DeleteBranchRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteBranchRequest) ProtoMessage()    {}
func (*DeleteBranchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_branches_bed202e6cba05c9f, []int{8}
}
func (m *DeleteBranchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBranchRequest.Unmarshal(m, b)
}
func (m *DeleteBranchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBranchRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteBranchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBranchRequest.Merge(dst, src)
}
func (m *DeleteBranchRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteBranchRequest.Size(m)
}
func (m *DeleteBranchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBranchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBranchRequest proto.InternalMessageInfo

func (m *DeleteBranchRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type BrancheOperation struct {
	Name                 string                         `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	OperationType        BrancheOperation_OperationType `protobuf:"varint,2,opt,name=operation_type,json=operationType,enum=erepro.api.branches.v1.BrancheOperation_OperationType" json:"operation_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *BrancheOperation) Reset()         { *m = BrancheOperation{} }
func (m *BrancheOperation) String() string { return proto.CompactTextString(m) }
func (*BrancheOperation) ProtoMessage()    {}
func (*BrancheOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_branches_bed202e6cba05c9f, []int{9}
}
func (m *BrancheOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrancheOperation.Unmarshal(m, b)
}
func (m *BrancheOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrancheOperation.Marshal(b, m, deterministic)
}
func (dst *BrancheOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrancheOperation.Merge(dst, src)
}
func (m *BrancheOperation) XXX_Size() int {
	return xxx_messageInfo_BrancheOperation.Size(m)
}
func (m *BrancheOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_BrancheOperation.DiscardUnknown(m)
}

var xxx_messageInfo_BrancheOperation proto.InternalMessageInfo

func (m *BrancheOperation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BrancheOperation) GetOperationType() BrancheOperation_OperationType {
	if m != nil {
		return m.OperationType
	}
	return BrancheOperation_OPERATION_TYPE_UNSPECIFIED
}

func init() {
	proto.RegisterType((*Branch)(nil), "erepro.api.branches.v1.Branch")
	proto.RegisterType((*ListBranchesRequest)(nil), "erepro.api.branches.v1.ListBranchesRequest")
	proto.RegisterType((*ListBranchesResponse)(nil), "erepro.api.branches.v1.ListBranchesResponse")
	proto.RegisterType((*SearchBranchesRequest)(nil), "erepro.api.branches.v1.SearchBranchesRequest")
	proto.RegisterType((*SearchBranchesResponse)(nil), "erepro.api.branches.v1.SearchBranchesResponse")
	proto.RegisterType((*GetBranchRequest)(nil), "erepro.api.branches.v1.GetBranchRequest")
	proto.RegisterType((*CreateBranchRequest)(nil), "erepro.api.branches.v1.CreateBranchRequest")
	proto.RegisterType((*UpdateBranchRequest)(nil), "erepro.api.branches.v1.UpdateBranchRequest")
	proto.RegisterType((*DeleteBranchRequest)(nil), "erepro.api.branches.v1.DeleteBranchRequest")
	proto.RegisterType((*BrancheOperation)(nil), "erepro.api.branches.v1.BrancheOperation")
	proto.RegisterEnum("erepro.api.branches.v1.BrancheOperation_OperationType", BrancheOperation_OperationType_name, BrancheOperation_OperationType_value)
}

func init() {
	proto.RegisterFile("erepro/api/branches/v1/branches.proto", fileDescriptor_branches_bed202e6cba05c9f)
}

var fileDescriptor_branches_bed202e6cba05c9f = []byte{
	// 816 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0x4d, 0x4f, 0xe3, 0x46,
	0x18, 0xae, 0x81, 0x7c, 0xf0, 0xe6, 0xa3, 0xd1, 0x24, 0x80, 0xeb, 0xf2, 0x91, 0xba, 0x2a, 0x4a,
	0x29, 0x75, 0x44, 0x2a, 0x71, 0x08, 0xea, 0x81, 0x40, 0xa8, 0x90, 0x0a, 0x44, 0x26, 0x1c, 0x7a,
	0xa8, 0x2c, 0x27, 0x1e, 0x12, 0x8b, 0xc4, 0x63, 0x3c, 0x0e, 0x25, 0x69, 0xab, 0x4a, 0xbd, 0xb5,
	0x97, 0x1e, 0xaa, 0x3d, 0xee, 0x9f, 0xd9, 0xbf, 0xb0, 0x7f, 0x61, 0x7f, 0xc8, 0x6a, 0xc6, 0x1f,
	0x38, 0x59, 0x67, 0xc3, 0x01, 0xed, 0x6d, 0xe6, 0x7d, 0x9f, 0x99, 0xf7, 0x7d, 0x66, 0x9e, 0x67,
	0x06, 0xbe, 0xc1, 0x0e, 0xb6, 0x1d, 0x52, 0xd5, 0x6d, 0xb3, 0xda, 0x71, 0x74, 0xab, 0xdb, 0xc7,
	0xb4, 0xfa, 0x70, 0x10, 0x8e, 0x15, 0xdb, 0x21, 0x2e, 0x41, 0xeb, 0x1e, 0x4c, 0xd1, 0x6d, 0x53,
	0x09, 0x53, 0x0f, 0x07, 0xd2, 0x66, 0x8f, 0x90, 0xde, 0x00, 0xf3, 0xe5, 0xba, 0x65, 0x11, 0x57,
	0x77, 0x4d, 0x62, 0xf9, 0xab, 0xa4, 0xaf, 0xfd, 0xec, 0x80, 0x58, 0x3d, 0x67, 0x64, 0x59, 0xa6,
	0xd5, 0xab, 0x12, 0x1b, 0x3b, 0x53, 0xa0, 0x1d, 0x1f, 0xc4, 0x67, 0x9d, 0xd1, 0x6d, 0xd5, 0x35,
	0x87, 0x98, 0xba, 0xfa, 0xd0, 0xf6, 0x01, 0xe5, 0x59, 0xc0, 0xad, 0x89, 0x07, 0x86, 0x36, 0xd4,
	0xe9, 0x9d, 0x87, 0x90, 0x5f, 0x2f, 0x41, 0xb2, 0xc1, 0xbb, 0x42, 0x08, 0x56, 0x2c, 0x7d, 0x88,
	0x45, 0xa1, 0x2c, 0x54, 0x56, 0x55, 0x3e, 0x46, 0x5f, 0x41, 0xd6, 0x30, 0xa9, 0x3d, 0xd0, 0xc7,
	0x1a, 0xcf, 0x2d, 0xf1, 0x5c, 0xc6, 0x8f, 0x5d, 0x32, 0x88, 0x08, 0x29, 0xdd, 0x30, 0x1c, 0x4c,
	0xa9, 0xb8, 0xcc, 0xb3, 0xc1, 0x14, 0x6d, 0x40, 0xca, 0x22, 0x5a, 0x07, 0x1b, 0x54, 0x5c, 0x29,
	0x0b, 0x95, 0x9c, 0x9a, 0xb4, 0x48, 0x03, 0x1b, 0x14, 0x7d, 0x01, 0x69, 0x96, 0xd0, 0xdd, 0x3e,
	0x15, 0x13, 0x3c, 0x93, 0xb2, 0x48, 0x83, 0x4d, 0x51, 0x09, 0x12, 0xb6, 0x63, 0x76, 0xb1, 0x98,
	0x2c, 0x0b, 0x95, 0x15, 0xd5, 0x9b, 0xa0, 0x23, 0xc8, 0x74, 0x1d, 0xac, 0xbb, 0x58, 0x63, 0x0c,
	0xc5, 0x54, 0x59, 0xa8, 0x64, 0x6a, 0x92, 0xe2, 0xb1, 0x53, 0x02, 0x76, 0x4a, 0x3b, 0xa0, 0xaf,
	0x82, 0x07, 0x67, 0x01, 0xb6, 0x78, 0x64, 0x1b, 0xe1, 0xe2, 0xf4, 0xe2, 0xc5, 0x1e, 0x9c, 0x05,
	0x64, 0x07, 0x8a, 0x3f, 0x9b, 0xd4, 0x6d, 0xf8, 0x17, 0xa7, 0xe2, 0xfb, 0x11, 0xa6, 0x2e, 0xfa,
	0x12, 0x56, 0x6d, 0xbd, 0x87, 0x35, 0x6a, 0x4e, 0xbc, 0x03, 0x4b, 0xa8, 0x69, 0x16, 0xb8, 0x36,
	0x27, 0x18, 0x6d, 0x01, 0xf0, 0xa4, 0x4b, 0xee, 0xb0, 0xe5, 0x1f, 0x19, 0x87, 0xb7, 0x59, 0x00,
	0xed, 0x40, 0x86, 0xf6, 0xc9, 0x6f, 0x9a, 0x81, 0x07, 0xd8, 0xc5, 0xfc, 0xd0, 0xd2, 0x2a, 0xb0,
	0xd0, 0x29, 0x8f, 0xc8, 0x13, 0x28, 0x4d, 0xd7, 0xa4, 0x36, 0xb1, 0x28, 0x46, 0x75, 0x48, 0x07,
	0x02, 0x12, 0x85, 0xf2, 0x72, 0x25, 0x53, 0xdb, 0x56, 0xe2, 0xc5, 0xa5, 0x78, 0x6b, 0xd5, 0x10,
	0x8f, 0x76, 0xe1, 0x73, 0x0b, 0x3f, 0xba, 0xda, 0x07, 0x8d, 0xe5, 0x58, 0xb8, 0x15, 0x34, 0x27,
	0x9b, 0xb0, 0x76, 0x8d, 0x75, 0xa7, 0xdb, 0x7f, 0x49, 0xc6, 0x25, 0x48, 0xdc, 0x8f, 0xb0, 0x33,
	0xf6, 0x05, 0xe2, 0x4d, 0xe4, 0x3f, 0x60, 0x7d, 0xb6, 0xd4, 0x27, 0x24, 0xba, 0x0b, 0x85, 0x9f,
	0xb0, 0x7f, 0xc6, 0x01, 0xc7, 0x18, 0x07, 0xc8, 0x17, 0x50, 0x3c, 0xe1, 0x5a, 0x9a, 0x86, 0x1e,
	0x42, 0xd2, 0x2b, 0xc9, 0xc1, 0x8b, 0x1b, 0xf4, 0xd1, 0xf2, 0xbf, 0x02, 0x14, 0x6f, 0xb8, 0xbc,
	0x5e, 0x64, 0xbf, 0x88, 0xb8, 0x99, 0xa9, 0x39, 0xd5, 0x38, 0x71, 0x9f, 0x31, 0xdf, 0x5f, 0xe8,
	0xf4, 0x2e, 0x10, 0x37, 0x1b, 0xcb, 0xdf, 0x42, 0xd1, 0x93, 0xdc, 0xe2, 0x63, 0x78, 0x23, 0x40,
	0xc1, 0xbf, 0xa7, 0xab, 0xe0, 0x19, 0x8a, 0x7d, 0x31, 0x7e, 0x85, 0x7c, 0xf8, 0x4e, 0x69, 0xee,
	0xd8, 0xf6, 0xde, 0x8c, 0x7c, 0xed, 0xf0, 0xe3, 0x84, 0x9e, 0x76, 0x55, 0xc2, 0x51, 0x7b, 0x6c,
	0x63, 0x35, 0x47, 0xa2, 0x53, 0xf9, 0x08, 0x72, 0x53, 0x79, 0xb4, 0x0d, 0xd2, 0x55, 0xab, 0xa9,
	0x1e, 0xb7, 0xcf, 0xaf, 0x2e, 0xb5, 0xf6, 0x2f, 0xad, 0xa6, 0x76, 0x73, 0x79, 0xdd, 0x6a, 0x9e,
	0x9c, 0x9f, 0x9d, 0x37, 0x4f, 0x0b, 0x9f, 0x21, 0x80, 0xe4, 0x89, 0xda, 0x3c, 0x6e, 0x37, 0x0b,
	0x42, 0xed, 0x55, 0x12, 0xd2, 0x81, 0xd8, 0xd0, 0x5f, 0x90, 0x8d, 0xba, 0x0c, 0x7d, 0x37, 0xaf,
	0xc1, 0x18, 0xff, 0x4b, 0xfb, 0xcf, 0x03, 0x7b, 0x7a, 0x96, 0x4b, 0x7f, 0xbf, 0x7d, 0xf7, 0xff,
	0x52, 0x1e, 0x65, 0xa3, 0xdf, 0x03, 0xfa, 0x4f, 0x80, 0xfc, 0xb4, 0x01, 0xd0, 0xf7, 0xf3, 0xb6,
	0x8d, 0xf5, 0xa4, 0xa4, 0x3c, 0x17, 0xee, 0xf7, 0xb1, 0xcd, 0xfb, 0x10, 0xe5, 0x62, 0xb4, 0x8f,
	0x3a, 0xe5, 0xe0, 0xba, 0xb0, 0x87, 0x5c, 0x58, 0x0d, 0x3d, 0x81, 0x2a, 0xf3, 0x36, 0x9f, 0xb5,
	0x8d, 0xb4, 0x40, 0xab, 0xf2, 0x16, 0x2f, 0xbb, 0x81, 0xd6, 0x58, 0xd9, 0xdf, 0x99, 0x4a, 0x7e,
	0x0c, 0xff, 0xcb, 0xbd, 0x3f, 0xd1, 0x23, 0x64, 0xa3, 0x0e, 0x9b, 0x7f, 0x11, 0x31, 0x3e, 0x94,
	0xb6, 0x02, 0xa9, 0x47, 0x3e, 0xca, 0x27, 0x05, 0xc9, 0x9b, 0xbc, 0xf4, 0xba, 0x3c, 0x75, 0xf2,
	0xf5, 0xc0, 0x3c, 0xff, 0x08, 0x90, 0x8d, 0x9a, 0x71, 0x7e, 0xe9, 0x18, 0xcb, 0x2e, 0xa4, 0xbd,
	0xcf, 0x6b, 0xef, 0xd6, 0x36, 0x39, 0x6d, 0x0f, 0xa0, 0xcc, 0xb2, 0x0f, 0x7b, 0x99, 0x40, 0x36,
	0xea, 0xc5, 0xf9, 0xad, 0xc4, 0x38, 0xf6, 0xb9, 0x37, 0xb0, 0x17, 0x7f, 0x03, 0x9d, 0x24, 0x7f,
	0x27, 0x7e, 0x78, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x91, 0xbf, 0x8a, 0x5c, 0xd2, 0x08, 0x00, 0x00,
}
