// Code generated by protoc-gen-go. DO NOT EDIT.
// source: erepro/api/listings/v1/listings.proto

package listings // import "github.com/eliaszs/erepro-apis/erepro/api/listings/v1"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "google.golang.org/genproto/googleapis/longrunning"
import field_mask "google.golang.org/genproto/protobuf/field_mask"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListingOperation_OperationType int32

const (
	ListingOperation_OPERATION_TYPE_UNSPECIFIED ListingOperation_OperationType = 0
	ListingOperation_CREATE                     ListingOperation_OperationType = 1
)

var ListingOperation_OperationType_name = map[int32]string{
	0: "OPERATION_TYPE_UNSPECIFIED",
	1: "CREATE",
}
var ListingOperation_OperationType_value = map[string]int32{
	"OPERATION_TYPE_UNSPECIFIED": 0,
	"CREATE":                     1,
}

func (x ListingOperation_OperationType) String() string {
	return proto.EnumName(ListingOperation_OperationType_name, int32(x))
}
func (ListingOperation_OperationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_listings_24605c445f6b7760, []int{9, 0}
}

type Listing struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	DisplayName          string               `protobuf:"bytes,2,opt,name=display_name,json=displayName" json:"display_name,omitempty"`
	Address              string               `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
	NoBeds               uint32               `protobuf:"varint,4,opt,name=no_beds,json=noBeds" json:"no_beds,omitempty"`
	NoBaths              uint32               `protobuf:"varint,5,opt,name=no_baths,json=noBaths" json:"no_baths,omitempty"`
	Price                uint64               `protobuf:"varint,6,opt,name=price" json:"price,omitempty"`
	Status               string               `protobuf:"bytes,7,opt,name=status" json:"status,omitempty"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,8,opt,name=create_time,json=createTime" json:"create_time,omitempty"`
	UpdateTime           *timestamp.Timestamp `protobuf:"bytes,9,opt,name=update_time,json=updateTime" json:"update_time,omitempty"`
	DeleteTime           *timestamp.Timestamp `protobuf:"bytes,10,opt,name=delete_time,json=deleteTime" json:"delete_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Listing) Reset()         { *m = Listing{} }
func (m *Listing) String() string { return proto.CompactTextString(m) }
func (*Listing) ProtoMessage()    {}
func (*Listing) Descriptor() ([]byte, []int) {
	return fileDescriptor_listings_24605c445f6b7760, []int{0}
}
func (m *Listing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listing.Unmarshal(m, b)
}
func (m *Listing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listing.Marshal(b, m, deterministic)
}
func (dst *Listing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listing.Merge(dst, src)
}
func (m *Listing) XXX_Size() int {
	return xxx_messageInfo_Listing.Size(m)
}
func (m *Listing) XXX_DiscardUnknown() {
	xxx_messageInfo_Listing.DiscardUnknown(m)
}

var xxx_messageInfo_Listing proto.InternalMessageInfo

func (m *Listing) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Listing) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Listing) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Listing) GetNoBeds() uint32 {
	if m != nil {
		return m.NoBeds
	}
	return 0
}

func (m *Listing) GetNoBaths() uint32 {
	if m != nil {
		return m.NoBaths
	}
	return 0
}

func (m *Listing) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Listing) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Listing) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *Listing) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

func (m *Listing) GetDeleteTime() *timestamp.Timestamp {
	if m != nil {
		return m.DeleteTime
	}
	return nil
}

type ListListingsRequest struct {
	PageSize             int32    `protobuf:"varint,1,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	PageToken            string   `protobuf:"bytes,2,opt,name=page_token,json=pageToken" json:"page_token,omitempty"`
	ShowDelete           bool     `protobuf:"varint,3,opt,name=show_delete,json=showDelete" json:"show_delete,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListListingsRequest) Reset()         { *m = ListListingsRequest{} }
func (m *ListListingsRequest) String() string { return proto.CompactTextString(m) }
func (*ListListingsRequest) ProtoMessage()    {}
func (*ListListingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_listings_24605c445f6b7760, []int{1}
}
func (m *ListListingsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListListingsRequest.Unmarshal(m, b)
}
func (m *ListListingsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListListingsRequest.Marshal(b, m, deterministic)
}
func (dst *ListListingsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListListingsRequest.Merge(dst, src)
}
func (m *ListListingsRequest) XXX_Size() int {
	return xxx_messageInfo_ListListingsRequest.Size(m)
}
func (m *ListListingsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListListingsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListListingsRequest proto.InternalMessageInfo

func (m *ListListingsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListListingsRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

func (m *ListListingsRequest) GetShowDelete() bool {
	if m != nil {
		return m.ShowDelete
	}
	return false
}

type ListListingsResponse struct {
	Listings             []*Listing `protobuf:"bytes,1,rep,name=listings" json:"listings,omitempty"`
	NextPageToken        string     `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListListingsResponse) Reset()         { *m = ListListingsResponse{} }
func (m *ListListingsResponse) String() string { return proto.CompactTextString(m) }
func (*ListListingsResponse) ProtoMessage()    {}
func (*ListListingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_listings_24605c445f6b7760, []int{2}
}
func (m *ListListingsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListListingsResponse.Unmarshal(m, b)
}
func (m *ListListingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListListingsResponse.Marshal(b, m, deterministic)
}
func (dst *ListListingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListListingsResponse.Merge(dst, src)
}
func (m *ListListingsResponse) XXX_Size() int {
	return xxx_messageInfo_ListListingsResponse.Size(m)
}
func (m *ListListingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListListingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListListingsResponse proto.InternalMessageInfo

func (m *ListListingsResponse) GetListings() []*Listing {
	if m != nil {
		return m.Listings
	}
	return nil
}

func (m *ListListingsResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type SearchListingsRequest struct {
	PageSize             int32    `protobuf:"varint,1,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	PageToken            string   `protobuf:"bytes,2,opt,name=page_token,json=pageToken" json:"page_token,omitempty"`
	Query                string   `protobuf:"bytes,3,opt,name=query" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchListingsRequest) Reset()         { *m = SearchListingsRequest{} }
func (m *SearchListingsRequest) String() string { return proto.CompactTextString(m) }
func (*SearchListingsRequest) ProtoMessage()    {}
func (*SearchListingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_listings_24605c445f6b7760, []int{3}
}
func (m *SearchListingsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchListingsRequest.Unmarshal(m, b)
}
func (m *SearchListingsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchListingsRequest.Marshal(b, m, deterministic)
}
func (dst *SearchListingsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchListingsRequest.Merge(dst, src)
}
func (m *SearchListingsRequest) XXX_Size() int {
	return xxx_messageInfo_SearchListingsRequest.Size(m)
}
func (m *SearchListingsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchListingsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchListingsRequest proto.InternalMessageInfo

func (m *SearchListingsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *SearchListingsRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

func (m *SearchListingsRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type SearchListingsResponse struct {
	Listings             []*Listing `protobuf:"bytes,1,rep,name=listings" json:"listings,omitempty"`
	NextPageToken        string     `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SearchListingsResponse) Reset()         { *m = SearchListingsResponse{} }
func (m *SearchListingsResponse) String() string { return proto.CompactTextString(m) }
func (*SearchListingsResponse) ProtoMessage()    {}
func (*SearchListingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_listings_24605c445f6b7760, []int{4}
}
func (m *SearchListingsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchListingsResponse.Unmarshal(m, b)
}
func (m *SearchListingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchListingsResponse.Marshal(b, m, deterministic)
}
func (dst *SearchListingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchListingsResponse.Merge(dst, src)
}
func (m *SearchListingsResponse) XXX_Size() int {
	return xxx_messageInfo_SearchListingsResponse.Size(m)
}
func (m *SearchListingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchListingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchListingsResponse proto.InternalMessageInfo

func (m *SearchListingsResponse) GetListings() []*Listing {
	if m != nil {
		return m.Listings
	}
	return nil
}

func (m *SearchListingsResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type GetListingRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListingRequest) Reset()         { *m = GetListingRequest{} }
func (m *GetListingRequest) String() string { return proto.CompactTextString(m) }
func (*GetListingRequest) ProtoMessage()    {}
func (*GetListingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_listings_24605c445f6b7760, []int{5}
}
func (m *GetListingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListingRequest.Unmarshal(m, b)
}
func (m *GetListingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListingRequest.Marshal(b, m, deterministic)
}
func (dst *GetListingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListingRequest.Merge(dst, src)
}
func (m *GetListingRequest) XXX_Size() int {
	return xxx_messageInfo_GetListingRequest.Size(m)
}
func (m *GetListingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetListingRequest proto.InternalMessageInfo

func (m *GetListingRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateListingRequest struct {
	Listing              *Listing `protobuf:"bytes,1,opt,name=listing" json:"listing,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateListingRequest) Reset()         { *m = CreateListingRequest{} }
func (m *CreateListingRequest) String() string { return proto.CompactTextString(m) }
func (*CreateListingRequest) ProtoMessage()    {}
func (*CreateListingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_listings_24605c445f6b7760, []int{6}
}
func (m *CreateListingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateListingRequest.Unmarshal(m, b)
}
func (m *CreateListingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateListingRequest.Marshal(b, m, deterministic)
}
func (dst *CreateListingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateListingRequest.Merge(dst, src)
}
func (m *CreateListingRequest) XXX_Size() int {
	return xxx_messageInfo_CreateListingRequest.Size(m)
}
func (m *CreateListingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateListingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateListingRequest proto.InternalMessageInfo

func (m *CreateListingRequest) GetListing() *Listing {
	if m != nil {
		return m.Listing
	}
	return nil
}

type UpdateListingRequest struct {
	Listing              *Listing              `protobuf:"bytes,1,opt,name=listing" json:"listing,omitempty"`
	UpdateMask           *field_mask.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateListingRequest) Reset()         { *m = UpdateListingRequest{} }
func (m *UpdateListingRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateListingRequest) ProtoMessage()    {}
func (*UpdateListingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_listings_24605c445f6b7760, []int{7}
}
func (m *UpdateListingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateListingRequest.Unmarshal(m, b)
}
func (m *UpdateListingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateListingRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateListingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateListingRequest.Merge(dst, src)
}
func (m *UpdateListingRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateListingRequest.Size(m)
}
func (m *UpdateListingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateListingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateListingRequest proto.InternalMessageInfo

func (m *UpdateListingRequest) GetListing() *Listing {
	if m != nil {
		return m.Listing
	}
	return nil
}

func (m *UpdateListingRequest) GetUpdateMask() *field_mask.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

type DeleteListingRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteListingRequest) Reset()         { *m = DeleteListingRequest{} }
func (m *DeleteListingRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteListingRequest) ProtoMessage()    {}
func (*DeleteListingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_listings_24605c445f6b7760, []int{8}
}
func (m *DeleteListingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteListingRequest.Unmarshal(m, b)
}
func (m *DeleteListingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteListingRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteListingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteListingRequest.Merge(dst, src)
}
func (m *DeleteListingRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteListingRequest.Size(m)
}
func (m *DeleteListingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteListingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteListingRequest proto.InternalMessageInfo

func (m *DeleteListingRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ListingOperation struct {
	Name                 string                         `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	OperationType        ListingOperation_OperationType `protobuf:"varint,2,opt,name=operation_type,json=operationType,enum=erepro.api.listings.v1.ListingOperation_OperationType" json:"operation_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *ListingOperation) Reset()         { *m = ListingOperation{} }
func (m *ListingOperation) String() string { return proto.CompactTextString(m) }
func (*ListingOperation) ProtoMessage()    {}
func (*ListingOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_listings_24605c445f6b7760, []int{9}
}
func (m *ListingOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListingOperation.Unmarshal(m, b)
}
func (m *ListingOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListingOperation.Marshal(b, m, deterministic)
}
func (dst *ListingOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListingOperation.Merge(dst, src)
}
func (m *ListingOperation) XXX_Size() int {
	return xxx_messageInfo_ListingOperation.Size(m)
}
func (m *ListingOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_ListingOperation.DiscardUnknown(m)
}

var xxx_messageInfo_ListingOperation proto.InternalMessageInfo

func (m *ListingOperation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListingOperation) GetOperationType() ListingOperation_OperationType {
	if m != nil {
		return m.OperationType
	}
	return ListingOperation_OPERATION_TYPE_UNSPECIFIED
}

func init() {
	proto.RegisterType((*Listing)(nil), "erepro.api.listings.v1.Listing")
	proto.RegisterType((*ListListingsRequest)(nil), "erepro.api.listings.v1.ListListingsRequest")
	proto.RegisterType((*ListListingsResponse)(nil), "erepro.api.listings.v1.ListListingsResponse")
	proto.RegisterType((*SearchListingsRequest)(nil), "erepro.api.listings.v1.SearchListingsRequest")
	proto.RegisterType((*SearchListingsResponse)(nil), "erepro.api.listings.v1.SearchListingsResponse")
	proto.RegisterType((*GetListingRequest)(nil), "erepro.api.listings.v1.GetListingRequest")
	proto.RegisterType((*CreateListingRequest)(nil), "erepro.api.listings.v1.CreateListingRequest")
	proto.RegisterType((*UpdateListingRequest)(nil), "erepro.api.listings.v1.UpdateListingRequest")
	proto.RegisterType((*DeleteListingRequest)(nil), "erepro.api.listings.v1.DeleteListingRequest")
	proto.RegisterType((*ListingOperation)(nil), "erepro.api.listings.v1.ListingOperation")
	proto.RegisterEnum("erepro.api.listings.v1.ListingOperation_OperationType", ListingOperation_OperationType_name, ListingOperation_OperationType_value)
}

func init() {
	proto.RegisterFile("erepro/api/listings/v1/listings.proto", fileDescriptor_listings_24605c445f6b7760)
}

var fileDescriptor_listings_24605c445f6b7760 = []byte{
	// 873 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xef, 0x6e, 0xe3, 0x44,
	0x10, 0xc7, 0xbd, 0x36, 0x49, 0x27, 0x4d, 0x29, 0x7b, 0xb9, 0x9e, 0x31, 0xe4, 0x1a, 0x8c, 0x80,
	0x10, 0x38, 0x5b, 0x17, 0x24, 0x24, 0x5a, 0x81, 0xb8, 0xf6, 0x72, 0xa8, 0x12, 0xb4, 0xc1, 0xcd,
	0x7d, 0x00, 0x09, 0x59, 0x9b, 0x78, 0x2f, 0x59, 0x35, 0xf1, 0xfa, 0xbc, 0xce, 0x1d, 0x69, 0x15,
	0x21, 0xf1, 0x00, 0xc7, 0x07, 0x1e, 0x81, 0x37, 0xe1, 0x15, 0x78, 0x05, 0xde, 0x80, 0x17, 0x40,
	0xbb, 0xf6, 0xba, 0x71, 0xce, 0x21, 0xf9, 0x70, 0xe2, 0xdb, 0xce, 0xcc, 0x6f, 0x76, 0xfe, 0xec,
	0xfc, 0xc6, 0x86, 0x0f, 0x48, 0x48, 0x82, 0x90, 0xd9, 0x38, 0xa0, 0xf6, 0x88, 0xf2, 0x88, 0xfa,
	0x03, 0x6e, 0x3f, 0x7f, 0x90, 0x9e, 0xad, 0x20, 0x64, 0x11, 0x43, 0xfb, 0x31, 0xcc, 0xc2, 0x01,
	0xb5, 0x52, 0xd3, 0xf3, 0x07, 0xc6, 0xbb, 0x03, 0xc6, 0x06, 0x23, 0x22, 0xdd, 0xb1, 0xef, 0xb3,
	0x08, 0x47, 0x94, 0xf9, 0x89, 0x97, 0xf1, 0x7e, 0x62, 0x1d, 0x31, 0x7f, 0x10, 0x4e, 0x7c, 0x9f,
	0xfa, 0x03, 0x9b, 0x05, 0x24, 0xcc, 0x80, 0x0e, 0x12, 0x90, 0x94, 0x7a, 0x93, 0xa7, 0x76, 0x44,
	0xc7, 0x84, 0x47, 0x78, 0x1c, 0x24, 0x80, 0xfa, 0x22, 0xe0, 0x29, 0x25, 0x23, 0xcf, 0x1d, 0x63,
	0x7e, 0x19, 0x23, 0xcc, 0x7f, 0x36, 0xa0, 0xf8, 0x6d, 0x9c, 0x15, 0x42, 0xb0, 0xe9, 0xe3, 0x31,
	0xd1, 0xb5, 0xba, 0xd6, 0xd8, 0x76, 0xe4, 0x19, 0xbd, 0x07, 0x3b, 0x1e, 0xe5, 0xc1, 0x08, 0x4f,
	0x5d, 0x69, 0xdb, 0x90, 0xb6, 0x72, 0xa2, 0x3b, 0x13, 0x10, 0x1d, 0x8a, 0xd8, 0xf3, 0x42, 0xc2,
	0xb9, 0x7e, 0x4b, 0x5a, 0x95, 0x88, 0xee, 0x42, 0xd1, 0x67, 0x6e, 0x8f, 0x78, 0x5c, 0xdf, 0xac,
	0x6b, 0x8d, 0x8a, 0x53, 0xf0, 0xd9, 0x31, 0xf1, 0x38, 0x7a, 0x1b, 0x4a, 0xc2, 0x80, 0xa3, 0x21,
	0xd7, 0xb7, 0xa4, 0xa5, 0xe8, 0xb3, 0x63, 0x21, 0xa2, 0x2a, 0x6c, 0x05, 0x21, 0xed, 0x13, 0xbd,
	0x50, 0xd7, 0x1a, 0x9b, 0x4e, 0x2c, 0xa0, 0x7d, 0x28, 0xf0, 0x08, 0x47, 0x13, 0xae, 0x17, 0x65,
	0x88, 0x44, 0x42, 0x47, 0x50, 0xee, 0x87, 0x04, 0x47, 0xc4, 0x15, 0xa5, 0xeb, 0xa5, 0xba, 0xd6,
	0x28, 0xb7, 0x0c, 0x2b, 0x2e, 0xdb, 0x52, 0x65, 0x5b, 0x5d, 0xd5, 0x17, 0x07, 0x62, 0xb8, 0x50,
	0x08, 0xe7, 0x49, 0xe0, 0xa5, 0xce, 0xdb, 0xab, 0x9d, 0x63, 0xb8, 0x72, 0xf6, 0xc8, 0x88, 0x28,
	0x67, 0x58, 0xed, 0x1c, 0xc3, 0x85, 0xc2, 0x0c, 0xe1, 0xb6, 0x68, 0x7a, 0xd2, 0x78, 0xee, 0x90,
	0x67, 0x13, 0xc2, 0x23, 0xf4, 0x0e, 0x6c, 0x07, 0x78, 0x40, 0x5c, 0x4e, 0xaf, 0xe2, 0x57, 0xd8,
	0x72, 0x4a, 0x42, 0x71, 0x41, 0xaf, 0x08, 0xaa, 0x01, 0x48, 0x63, 0xc4, 0x2e, 0x89, 0x9f, 0xbc,
	0x83, 0x84, 0x77, 0x85, 0x02, 0x1d, 0x40, 0x99, 0x0f, 0xd9, 0x0b, 0x37, 0x8e, 0x22, 0x5f, 0xa2,
	0xe4, 0x80, 0x50, 0x3d, 0x92, 0x1a, 0xf3, 0x1a, 0xaa, 0xd9, 0x98, 0x3c, 0x60, 0x3e, 0x17, 0x85,
	0x94, 0xd4, 0x58, 0xea, 0x5a, 0xfd, 0x56, 0xa3, 0xdc, 0x3a, 0xb0, 0xf2, 0x47, 0xd6, 0x4a, 0x7c,
	0x9d, 0xd4, 0x01, 0x7d, 0x08, 0x6f, 0xfa, 0xe4, 0xe7, 0xc8, 0x7d, 0x25, 0xb3, 0x8a, 0x50, 0x77,
	0x54, 0x76, 0x26, 0x85, 0x3b, 0x17, 0x04, 0x87, 0xfd, 0xe1, 0xeb, 0x2c, 0xb9, 0x0a, 0x5b, 0xcf,
	0x26, 0x24, 0x9c, 0x26, 0x63, 0x17, 0x0b, 0xe6, 0x0c, 0xf6, 0x17, 0x43, 0xfd, 0x9f, 0x95, 0x7e,
	0x04, 0x6f, 0x7d, 0x43, 0x54, 0x97, 0x55, 0x95, 0x39, 0xcc, 0x32, 0xbf, 0x87, 0xea, 0x89, 0x9c,
	0xc5, 0x05, 0xec, 0x17, 0x50, 0x4c, 0x82, 0x4a, 0xf8, 0x1a, 0x49, 0x2a, 0xbc, 0xf9, 0x52, 0x83,
	0xea, 0x13, 0x39, 0xa2, 0xaf, 0xed, 0xce, 0x39, 0x92, 0x88, 0xad, 0x21, 0x6b, 0xce, 0x9b, 0xf3,
	0xc7, 0x62, 0xb1, 0x7c, 0x87, 0xf9, 0xa5, 0x22, 0x89, 0x38, 0x9b, 0x4d, 0xa8, 0xc6, 0xd3, 0xb7,
	0x46, 0x3f, 0xfe, 0xd4, 0x60, 0x2f, 0x81, 0x9d, 0xab, 0x45, 0x97, 0xbb, 0x92, 0x7e, 0x82, 0xdd,
	0x74, 0x13, 0xba, 0xd1, 0x34, 0x88, 0x97, 0xd2, 0x6e, 0xeb, 0xf3, 0x15, 0x35, 0xa5, 0xb7, 0x5a,
	0xe9, 0xa9, 0x3b, 0x0d, 0x88, 0x53, 0x61, 0xf3, 0xa2, 0x79, 0x04, 0x95, 0x8c, 0x1d, 0xdd, 0x03,
	0xe3, 0xbc, 0xd3, 0x76, 0x1e, 0x76, 0x4f, 0xcf, 0xcf, 0xdc, 0xee, 0x0f, 0x9d, 0xb6, 0xfb, 0xe4,
	0xec, 0xa2, 0xd3, 0x3e, 0x39, 0x7d, 0x7c, 0xda, 0x7e, 0xb4, 0xf7, 0x06, 0x02, 0x28, 0x9c, 0x38,
	0xed, 0x87, 0xdd, 0xf6, 0x9e, 0xd6, 0xfa, 0xa3, 0x00, 0x25, 0x35, 0x77, 0xe8, 0x17, 0xd8, 0x99,
	0x67, 0x1c, 0xfa, 0xe4, 0xbf, 0x12, 0x5c, 0x20, 0x86, 0xf1, 0xe9, 0x7a, 0xe0, 0x78, 0xb4, 0xcd,
	0xea, 0xaf, 0x7f, 0xfd, 0xfd, 0xfb, 0xc6, 0x2e, 0xda, 0x99, 0xff, 0x00, 0xa1, 0xdf, 0x34, 0xd8,
	0xcd, 0x72, 0x01, 0xdd, 0x5f, 0x76, 0x6d, 0x2e, 0x3d, 0x0d, 0x6b, 0x5d, 0x78, 0x92, 0xc7, 0x3d,
	0x99, 0x87, 0x6e, 0xde, 0x9e, 0xcf, 0xe3, 0x90, 0x4b, 0xf0, 0xa1, 0xd6, 0x44, 0x2f, 0x00, 0x6e,
	0xd8, 0x81, 0x3e, 0x5e, 0x76, 0xfb, 0x2b, 0x0c, 0x32, 0x56, 0x0d, 0xac, 0x59, 0x93, 0x91, 0xef,
	0xa2, 0x3b, 0x22, 0xf2, 0xb5, 0x18, 0x94, 0x2f, 0x15, 0x6c, 0x66, 0x37, 0xd1, 0x35, 0x54, 0x32,
	0x6c, 0x43, 0x4b, 0xfb, 0x9b, 0x47, 0x4a, 0xa3, 0xa6, 0x06, 0x7e, 0xee, 0x7b, 0x7c, 0x33, 0x46,
	0x2a, 0xb8, 0x99, 0x69, 0xff, 0x61, 0xca, 0xa1, 0x97, 0x1a, 0x54, 0x32, 0xbc, 0x5c, 0x1e, 0x3d,
	0x8f, 0xbe, 0xab, 0x8b, 0xb7, 0x64, 0xfc, 0x46, 0xab, 0x26, 0x8b, 0x4f, 0x10, 0x56, 0xa6, 0x09,
	0x76, 0x73, 0x76, 0x93, 0xd0, 0x0c, 0x2a, 0x19, 0x5e, 0x2e, 0xcf, 0x27, 0x8f, 0xbe, 0x6b, 0x3f,
	0x46, 0x33, 0xe7, 0x31, 0xec, 0xe6, 0xec, 0xf8, 0xeb, 0x1f, 0xbf, 0x1a, 0xd0, 0x68, 0x38, 0xe9,
	0x59, 0x7d, 0x36, 0xb6, 0xc9, 0x88, 0x62, 0x7e, 0xc5, 0xed, 0xf8, 0xce, 0xfb, 0x38, 0xa0, 0xea,
	0xbc, 0xf8, 0x6b, 0x75, 0xa4, 0xce, 0xbd, 0x82, 0x5c, 0x3c, 0x9f, 0xfd, 0x1b, 0x00, 0x00, 0xff,
	0xff, 0x29, 0x8b, 0xf0, 0x13, 0x84, 0x09, 0x00, 0x00,
}
