// Code generated by protoc-gen-go. DO NOT EDIT.
// source: erepro/api/listings/v1/listings.proto

package listings // import "github.com/eliaszs/erepro-apis/erepro/api/listings/v1"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import field_mask "google.golang.org/genproto/protobuf/field_mask"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListingOperation_OperationType int32

const (
	ListingOperation_OPERATION_TYPE_UNSPECIFIED ListingOperation_OperationType = 0
	ListingOperation_CREATE                     ListingOperation_OperationType = 1
)

var ListingOperation_OperationType_name = map[int32]string{
	0: "OPERATION_TYPE_UNSPECIFIED",
	1: "CREATE",
}
var ListingOperation_OperationType_value = map[string]int32{
	"OPERATION_TYPE_UNSPECIFIED": 0,
	"CREATE":                     1,
}

func (x ListingOperation_OperationType) String() string {
	return proto.EnumName(ListingOperation_OperationType_name, int32(x))
}
func (ListingOperation_OperationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_listings_0f8a8d737c4c7a4e, []int{9, 0}
}

type Listing struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	DisplayName          string               `protobuf:"bytes,2,opt,name=display_name,json=displayName" json:"display_name,omitempty"`
	Address              string               `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
	NoBeds               uint32               `protobuf:"varint,4,opt,name=no_beds,json=noBeds" json:"no_beds,omitempty"`
	NoBaths              uint32               `protobuf:"varint,5,opt,name=no_baths,json=noBaths" json:"no_baths,omitempty"`
	Price                uint64               `protobuf:"varint,6,opt,name=price" json:"price,omitempty"`
	Status               string               `protobuf:"bytes,7,opt,name=status" json:"status,omitempty"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,8,opt,name=create_time,json=createTime" json:"create_time,omitempty"`
	UpdateTime           *timestamp.Timestamp `protobuf:"bytes,9,opt,name=update_time,json=updateTime" json:"update_time,omitempty"`
	DeleteTime           *timestamp.Timestamp `protobuf:"bytes,10,opt,name=delete_time,json=deleteTime" json:"delete_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Listing) Reset()         { *m = Listing{} }
func (m *Listing) String() string { return proto.CompactTextString(m) }
func (*Listing) ProtoMessage()    {}
func (*Listing) Descriptor() ([]byte, []int) {
	return fileDescriptor_listings_0f8a8d737c4c7a4e, []int{0}
}
func (m *Listing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listing.Unmarshal(m, b)
}
func (m *Listing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listing.Marshal(b, m, deterministic)
}
func (dst *Listing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listing.Merge(dst, src)
}
func (m *Listing) XXX_Size() int {
	return xxx_messageInfo_Listing.Size(m)
}
func (m *Listing) XXX_DiscardUnknown() {
	xxx_messageInfo_Listing.DiscardUnknown(m)
}

var xxx_messageInfo_Listing proto.InternalMessageInfo

func (m *Listing) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Listing) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Listing) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Listing) GetNoBeds() uint32 {
	if m != nil {
		return m.NoBeds
	}
	return 0
}

func (m *Listing) GetNoBaths() uint32 {
	if m != nil {
		return m.NoBaths
	}
	return 0
}

func (m *Listing) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Listing) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Listing) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *Listing) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

func (m *Listing) GetDeleteTime() *timestamp.Timestamp {
	if m != nil {
		return m.DeleteTime
	}
	return nil
}

type ListListingsRequest struct {
	PageSize             int32    `protobuf:"varint,1,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	PageToken            string   `protobuf:"bytes,2,opt,name=page_token,json=pageToken" json:"page_token,omitempty"`
	ShowDelete           bool     `protobuf:"varint,3,opt,name=show_delete,json=showDelete" json:"show_delete,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListListingsRequest) Reset()         { *m = ListListingsRequest{} }
func (m *ListListingsRequest) String() string { return proto.CompactTextString(m) }
func (*ListListingsRequest) ProtoMessage()    {}
func (*ListListingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_listings_0f8a8d737c4c7a4e, []int{1}
}
func (m *ListListingsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListListingsRequest.Unmarshal(m, b)
}
func (m *ListListingsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListListingsRequest.Marshal(b, m, deterministic)
}
func (dst *ListListingsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListListingsRequest.Merge(dst, src)
}
func (m *ListListingsRequest) XXX_Size() int {
	return xxx_messageInfo_ListListingsRequest.Size(m)
}
func (m *ListListingsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListListingsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListListingsRequest proto.InternalMessageInfo

func (m *ListListingsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListListingsRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

func (m *ListListingsRequest) GetShowDelete() bool {
	if m != nil {
		return m.ShowDelete
	}
	return false
}

type ListListingsResponse struct {
	Listings             []*Listing `protobuf:"bytes,1,rep,name=listings" json:"listings,omitempty"`
	NextPageToken        string     `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListListingsResponse) Reset()         { *m = ListListingsResponse{} }
func (m *ListListingsResponse) String() string { return proto.CompactTextString(m) }
func (*ListListingsResponse) ProtoMessage()    {}
func (*ListListingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_listings_0f8a8d737c4c7a4e, []int{2}
}
func (m *ListListingsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListListingsResponse.Unmarshal(m, b)
}
func (m *ListListingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListListingsResponse.Marshal(b, m, deterministic)
}
func (dst *ListListingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListListingsResponse.Merge(dst, src)
}
func (m *ListListingsResponse) XXX_Size() int {
	return xxx_messageInfo_ListListingsResponse.Size(m)
}
func (m *ListListingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListListingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListListingsResponse proto.InternalMessageInfo

func (m *ListListingsResponse) GetListings() []*Listing {
	if m != nil {
		return m.Listings
	}
	return nil
}

func (m *ListListingsResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type SearchListingsRequest struct {
	PageSize             int32    `protobuf:"varint,1,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	PageToken            string   `protobuf:"bytes,2,opt,name=page_token,json=pageToken" json:"page_token,omitempty"`
	Query                string   `protobuf:"bytes,3,opt,name=query" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchListingsRequest) Reset()         { *m = SearchListingsRequest{} }
func (m *SearchListingsRequest) String() string { return proto.CompactTextString(m) }
func (*SearchListingsRequest) ProtoMessage()    {}
func (*SearchListingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_listings_0f8a8d737c4c7a4e, []int{3}
}
func (m *SearchListingsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchListingsRequest.Unmarshal(m, b)
}
func (m *SearchListingsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchListingsRequest.Marshal(b, m, deterministic)
}
func (dst *SearchListingsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchListingsRequest.Merge(dst, src)
}
func (m *SearchListingsRequest) XXX_Size() int {
	return xxx_messageInfo_SearchListingsRequest.Size(m)
}
func (m *SearchListingsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchListingsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchListingsRequest proto.InternalMessageInfo

func (m *SearchListingsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *SearchListingsRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

func (m *SearchListingsRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type SearchListingsResponse struct {
	Listings             []*Listing `protobuf:"bytes,1,rep,name=listings" json:"listings,omitempty"`
	NextPageToken        string     `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SearchListingsResponse) Reset()         { *m = SearchListingsResponse{} }
func (m *SearchListingsResponse) String() string { return proto.CompactTextString(m) }
func (*SearchListingsResponse) ProtoMessage()    {}
func (*SearchListingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_listings_0f8a8d737c4c7a4e, []int{4}
}
func (m *SearchListingsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchListingsResponse.Unmarshal(m, b)
}
func (m *SearchListingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchListingsResponse.Marshal(b, m, deterministic)
}
func (dst *SearchListingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchListingsResponse.Merge(dst, src)
}
func (m *SearchListingsResponse) XXX_Size() int {
	return xxx_messageInfo_SearchListingsResponse.Size(m)
}
func (m *SearchListingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchListingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchListingsResponse proto.InternalMessageInfo

func (m *SearchListingsResponse) GetListings() []*Listing {
	if m != nil {
		return m.Listings
	}
	return nil
}

func (m *SearchListingsResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type GetListingRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListingRequest) Reset()         { *m = GetListingRequest{} }
func (m *GetListingRequest) String() string { return proto.CompactTextString(m) }
func (*GetListingRequest) ProtoMessage()    {}
func (*GetListingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_listings_0f8a8d737c4c7a4e, []int{5}
}
func (m *GetListingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListingRequest.Unmarshal(m, b)
}
func (m *GetListingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListingRequest.Marshal(b, m, deterministic)
}
func (dst *GetListingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListingRequest.Merge(dst, src)
}
func (m *GetListingRequest) XXX_Size() int {
	return xxx_messageInfo_GetListingRequest.Size(m)
}
func (m *GetListingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetListingRequest proto.InternalMessageInfo

func (m *GetListingRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateListingRequest struct {
	Listing              *Listing `protobuf:"bytes,1,opt,name=listing" json:"listing,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateListingRequest) Reset()         { *m = CreateListingRequest{} }
func (m *CreateListingRequest) String() string { return proto.CompactTextString(m) }
func (*CreateListingRequest) ProtoMessage()    {}
func (*CreateListingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_listings_0f8a8d737c4c7a4e, []int{6}
}
func (m *CreateListingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateListingRequest.Unmarshal(m, b)
}
func (m *CreateListingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateListingRequest.Marshal(b, m, deterministic)
}
func (dst *CreateListingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateListingRequest.Merge(dst, src)
}
func (m *CreateListingRequest) XXX_Size() int {
	return xxx_messageInfo_CreateListingRequest.Size(m)
}
func (m *CreateListingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateListingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateListingRequest proto.InternalMessageInfo

func (m *CreateListingRequest) GetListing() *Listing {
	if m != nil {
		return m.Listing
	}
	return nil
}

type UpdateListingRequest struct {
	Listing              *Listing              `protobuf:"bytes,1,opt,name=listing" json:"listing,omitempty"`
	UpdateMask           *field_mask.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateListingRequest) Reset()         { *m = UpdateListingRequest{} }
func (m *UpdateListingRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateListingRequest) ProtoMessage()    {}
func (*UpdateListingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_listings_0f8a8d737c4c7a4e, []int{7}
}
func (m *UpdateListingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateListingRequest.Unmarshal(m, b)
}
func (m *UpdateListingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateListingRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateListingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateListingRequest.Merge(dst, src)
}
func (m *UpdateListingRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateListingRequest.Size(m)
}
func (m *UpdateListingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateListingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateListingRequest proto.InternalMessageInfo

func (m *UpdateListingRequest) GetListing() *Listing {
	if m != nil {
		return m.Listing
	}
	return nil
}

func (m *UpdateListingRequest) GetUpdateMask() *field_mask.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

type DeleteListingRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteListingRequest) Reset()         { *m = DeleteListingRequest{} }
func (m *DeleteListingRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteListingRequest) ProtoMessage()    {}
func (*DeleteListingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_listings_0f8a8d737c4c7a4e, []int{8}
}
func (m *DeleteListingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteListingRequest.Unmarshal(m, b)
}
func (m *DeleteListingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteListingRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteListingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteListingRequest.Merge(dst, src)
}
func (m *DeleteListingRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteListingRequest.Size(m)
}
func (m *DeleteListingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteListingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteListingRequest proto.InternalMessageInfo

func (m *DeleteListingRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ListingOperation struct {
	Name                 string                         `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	OperationType        ListingOperation_OperationType `protobuf:"varint,2,opt,name=operation_type,json=operationType,enum=erepro.api.listings.v1.ListingOperation_OperationType" json:"operation_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *ListingOperation) Reset()         { *m = ListingOperation{} }
func (m *ListingOperation) String() string { return proto.CompactTextString(m) }
func (*ListingOperation) ProtoMessage()    {}
func (*ListingOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_listings_0f8a8d737c4c7a4e, []int{9}
}
func (m *ListingOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListingOperation.Unmarshal(m, b)
}
func (m *ListingOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListingOperation.Marshal(b, m, deterministic)
}
func (dst *ListingOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListingOperation.Merge(dst, src)
}
func (m *ListingOperation) XXX_Size() int {
	return xxx_messageInfo_ListingOperation.Size(m)
}
func (m *ListingOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_ListingOperation.DiscardUnknown(m)
}

var xxx_messageInfo_ListingOperation proto.InternalMessageInfo

func (m *ListingOperation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListingOperation) GetOperationType() ListingOperation_OperationType {
	if m != nil {
		return m.OperationType
	}
	return ListingOperation_OPERATION_TYPE_UNSPECIFIED
}

func init() {
	proto.RegisterType((*Listing)(nil), "erepro.api.listings.v1.Listing")
	proto.RegisterType((*ListListingsRequest)(nil), "erepro.api.listings.v1.ListListingsRequest")
	proto.RegisterType((*ListListingsResponse)(nil), "erepro.api.listings.v1.ListListingsResponse")
	proto.RegisterType((*SearchListingsRequest)(nil), "erepro.api.listings.v1.SearchListingsRequest")
	proto.RegisterType((*SearchListingsResponse)(nil), "erepro.api.listings.v1.SearchListingsResponse")
	proto.RegisterType((*GetListingRequest)(nil), "erepro.api.listings.v1.GetListingRequest")
	proto.RegisterType((*CreateListingRequest)(nil), "erepro.api.listings.v1.CreateListingRequest")
	proto.RegisterType((*UpdateListingRequest)(nil), "erepro.api.listings.v1.UpdateListingRequest")
	proto.RegisterType((*DeleteListingRequest)(nil), "erepro.api.listings.v1.DeleteListingRequest")
	proto.RegisterType((*ListingOperation)(nil), "erepro.api.listings.v1.ListingOperation")
	proto.RegisterEnum("erepro.api.listings.v1.ListingOperation_OperationType", ListingOperation_OperationType_name, ListingOperation_OperationType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ListingsClient is the client API for Listings service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ListingsClient interface {
	// List the availalbe listings
	ListListings(ctx context.Context, in *ListListingsRequest, opts ...grpc.CallOption) (*ListListingsResponse, error)
	// Search for listings that match specific filter criteria.
	SearchListings(ctx context.Context, in *SearchListingsRequest, opts ...grpc.CallOption) (*SearchListingsResponse, error)
	// Retrives a listing identified by the supplied listing name
	GetListing(ctx context.Context, in *GetListingRequest, opts ...grpc.CallOption) (*Listing, error)
	// Create a listing in the database
	CreateListing(ctx context.Context, in *CreateListingRequest, opts ...grpc.CallOption) (*Listing, error)
	// Update a listing
	UpdateListing(ctx context.Context, in *UpdateListingRequest, opts ...grpc.CallOption) (*Listing, error)
	// Delete a listing
	DeleteListing(ctx context.Context, in *DeleteListingRequest, opts ...grpc.CallOption) (*Listing, error)
}

type listingsClient struct {
	cc *grpc.ClientConn
}

func NewListingsClient(cc *grpc.ClientConn) ListingsClient {
	return &listingsClient{cc}
}

func (c *listingsClient) ListListings(ctx context.Context, in *ListListingsRequest, opts ...grpc.CallOption) (*ListListingsResponse, error) {
	out := new(ListListingsResponse)
	err := c.cc.Invoke(ctx, "/erepro.api.listings.v1.Listings/ListListings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listingsClient) SearchListings(ctx context.Context, in *SearchListingsRequest, opts ...grpc.CallOption) (*SearchListingsResponse, error) {
	out := new(SearchListingsResponse)
	err := c.cc.Invoke(ctx, "/erepro.api.listings.v1.Listings/SearchListings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listingsClient) GetListing(ctx context.Context, in *GetListingRequest, opts ...grpc.CallOption) (*Listing, error) {
	out := new(Listing)
	err := c.cc.Invoke(ctx, "/erepro.api.listings.v1.Listings/GetListing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listingsClient) CreateListing(ctx context.Context, in *CreateListingRequest, opts ...grpc.CallOption) (*Listing, error) {
	out := new(Listing)
	err := c.cc.Invoke(ctx, "/erepro.api.listings.v1.Listings/CreateListing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listingsClient) UpdateListing(ctx context.Context, in *UpdateListingRequest, opts ...grpc.CallOption) (*Listing, error) {
	out := new(Listing)
	err := c.cc.Invoke(ctx, "/erepro.api.listings.v1.Listings/UpdateListing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listingsClient) DeleteListing(ctx context.Context, in *DeleteListingRequest, opts ...grpc.CallOption) (*Listing, error) {
	out := new(Listing)
	err := c.cc.Invoke(ctx, "/erepro.api.listings.v1.Listings/DeleteListing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListingsServer is the server API for Listings service.
type ListingsServer interface {
	// List the availalbe listings
	ListListings(context.Context, *ListListingsRequest) (*ListListingsResponse, error)
	// Search for listings that match specific filter criteria.
	SearchListings(context.Context, *SearchListingsRequest) (*SearchListingsResponse, error)
	// Retrives a listing identified by the supplied listing name
	GetListing(context.Context, *GetListingRequest) (*Listing, error)
	// Create a listing in the database
	CreateListing(context.Context, *CreateListingRequest) (*Listing, error)
	// Update a listing
	UpdateListing(context.Context, *UpdateListingRequest) (*Listing, error)
	// Delete a listing
	DeleteListing(context.Context, *DeleteListingRequest) (*Listing, error)
}

func RegisterListingsServer(s *grpc.Server, srv ListingsServer) {
	s.RegisterService(&_Listings_serviceDesc, srv)
}

func _Listings_ListListings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListListingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListingsServer).ListListings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/erepro.api.listings.v1.Listings/ListListings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListingsServer).ListListings(ctx, req.(*ListListingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Listings_SearchListings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchListingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListingsServer).SearchListings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/erepro.api.listings.v1.Listings/SearchListings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListingsServer).SearchListings(ctx, req.(*SearchListingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Listings_GetListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListingsServer).GetListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/erepro.api.listings.v1.Listings/GetListing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListingsServer).GetListing(ctx, req.(*GetListingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Listings_CreateListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateListingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListingsServer).CreateListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/erepro.api.listings.v1.Listings/CreateListing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListingsServer).CreateListing(ctx, req.(*CreateListingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Listings_UpdateListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateListingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListingsServer).UpdateListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/erepro.api.listings.v1.Listings/UpdateListing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListingsServer).UpdateListing(ctx, req.(*UpdateListingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Listings_DeleteListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteListingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListingsServer).DeleteListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/erepro.api.listings.v1.Listings/DeleteListing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListingsServer).DeleteListing(ctx, req.(*DeleteListingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Listings_serviceDesc = grpc.ServiceDesc{
	ServiceName: "erepro.api.listings.v1.Listings",
	HandlerType: (*ListingsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListListings",
			Handler:    _Listings_ListListings_Handler,
		},
		{
			MethodName: "SearchListings",
			Handler:    _Listings_SearchListings_Handler,
		},
		{
			MethodName: "GetListing",
			Handler:    _Listings_GetListing_Handler,
		},
		{
			MethodName: "CreateListing",
			Handler:    _Listings_CreateListing_Handler,
		},
		{
			MethodName: "UpdateListing",
			Handler:    _Listings_UpdateListing_Handler,
		},
		{
			MethodName: "DeleteListing",
			Handler:    _Listings_DeleteListing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "erepro/api/listings/v1/listings.proto",
}

func init() {
	proto.RegisterFile("erepro/api/listings/v1/listings.proto", fileDescriptor_listings_0f8a8d737c4c7a4e)
}

var fileDescriptor_listings_0f8a8d737c4c7a4e = []byte{
	// 847 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xdd, 0x6e, 0xeb, 0x44,
	0x10, 0xc6, 0x3d, 0xcd, 0x4f, 0x27, 0x4d, 0x28, 0x7b, 0x72, 0x7a, 0x4c, 0xa0, 0x6d, 0xb0, 0x04,
	0x84, 0x40, 0x6d, 0x35, 0x48, 0x48, 0xb4, 0x02, 0xd1, 0x9f, 0x14, 0x55, 0x82, 0x36, 0xb8, 0xe9,
	0x05, 0x48, 0xc8, 0xda, 0xc4, 0xdb, 0xc4, 0x6a, 0xe2, 0x75, 0xbd, 0x4e, 0x4b, 0x5a, 0x45, 0x48,
	0x3c, 0x40, 0xb9, 0xe0, 0x19, 0x78, 0x11, 0x5e, 0x81, 0x57, 0xe0, 0x0d, 0x78, 0x01, 0xb4, 0x6b,
	0x6f, 0x1a, 0xa7, 0x0e, 0xc9, 0x45, 0x75, 0xee, 0x76, 0x66, 0xbe, 0xd9, 0xf9, 0xd9, 0xf9, 0xc6,
	0x86, 0x0f, 0x89, 0x4f, 0x3c, 0x9f, 0x1a, 0xd8, 0x73, 0x8c, 0x9e, 0xc3, 0x02, 0xc7, 0xed, 0x30,
	0xe3, 0x66, 0x67, 0x7c, 0xd6, 0x3d, 0x9f, 0x06, 0x14, 0xad, 0x87, 0x30, 0x1d, 0x7b, 0x8e, 0x3e,
	0x36, 0xdd, 0xec, 0x94, 0xde, 0xef, 0x50, 0xda, 0xe9, 0x11, 0xe1, 0x8e, 0x5d, 0x97, 0x06, 0x38,
	0x70, 0xa8, 0x1b, 0x79, 0x95, 0xb6, 0x22, 0xab, 0x90, 0x5a, 0x83, 0x4b, 0x23, 0x70, 0xfa, 0x84,
	0x05, 0xb8, 0xef, 0x45, 0x80, 0xf2, 0x34, 0xe0, 0xd2, 0x21, 0x3d, 0xdb, 0xea, 0x63, 0x76, 0x15,
	0x22, 0xb4, 0x7f, 0x97, 0x20, 0xf3, 0x5d, 0x18, 0x10, 0x21, 0x58, 0x76, 0x71, 0x9f, 0xa8, 0x4a,
	0x59, 0xa9, 0xac, 0x98, 0xe2, 0x8c, 0x3e, 0x80, 0x55, 0xdb, 0x61, 0x5e, 0x0f, 0x0f, 0x2d, 0x61,
	0x5b, 0x12, 0xb6, 0x5c, 0xa4, 0x3b, 0xe5, 0x10, 0x15, 0x32, 0xd8, 0xb6, 0x7d, 0xc2, 0x98, 0xfa,
	0x42, 0x58, 0xa5, 0x88, 0x5e, 0x43, 0xc6, 0xa5, 0x56, 0x8b, 0xd8, 0x4c, 0x5d, 0x2e, 0x2b, 0x95,
	0xbc, 0x99, 0x76, 0xe9, 0x01, 0xb1, 0x19, 0x7a, 0x17, 0xb2, 0xdc, 0x80, 0x83, 0x2e, 0x53, 0x53,
	0xc2, 0x92, 0x71, 0xe9, 0x01, 0x17, 0x51, 0x11, 0x52, 0x9e, 0xef, 0xb4, 0x89, 0x9a, 0x2e, 0x2b,
	0x95, 0x65, 0x33, 0x14, 0xd0, 0x3a, 0xa4, 0x59, 0x80, 0x83, 0x01, 0x53, 0x33, 0x22, 0x44, 0x24,
	0xa1, 0x3d, 0xc8, 0xb5, 0x7d, 0x82, 0x03, 0x62, 0xf1, 0xd2, 0xd5, 0x6c, 0x59, 0xa9, 0xe4, 0x6a,
	0x25, 0x3d, 0x2c, 0x5b, 0x97, 0x65, 0xeb, 0x4d, 0xd9, 0x17, 0x13, 0x42, 0x38, 0x57, 0x70, 0xe7,
	0x81, 0x67, 0x8f, 0x9d, 0x57, 0xe6, 0x3b, 0x87, 0x70, 0xe9, 0x6c, 0x93, 0x1e, 0x91, 0xce, 0x30,
	0xdf, 0x39, 0x84, 0x73, 0x85, 0xe6, 0xc3, 0x4b, 0xde, 0xf4, 0xa8, 0xf1, 0xcc, 0x24, 0xd7, 0x03,
	0xc2, 0x02, 0xf4, 0x1e, 0xac, 0x78, 0xb8, 0x43, 0x2c, 0xe6, 0xdc, 0x85, 0xaf, 0x90, 0x32, 0xb3,
	0x5c, 0x71, 0xee, 0xdc, 0x11, 0xb4, 0x01, 0x20, 0x8c, 0x01, 0xbd, 0x22, 0x6e, 0xf4, 0x0e, 0x02,
	0xde, 0xe4, 0x0a, 0xb4, 0x05, 0x39, 0xd6, 0xa5, 0xb7, 0x56, 0x18, 0x45, 0xbc, 0x44, 0xd6, 0x04,
	0xae, 0x3a, 0x12, 0x1a, 0xed, 0x1e, 0x8a, 0xf1, 0x98, 0xcc, 0xa3, 0x2e, 0xe3, 0x85, 0x64, 0xe5,
	0xc4, 0xa9, 0x4a, 0xf9, 0x45, 0x25, 0x57, 0xdb, 0xd2, 0x93, 0xa7, 0x51, 0x8f, 0x7c, 0xcd, 0xb1,
	0x03, 0xfa, 0x08, 0xde, 0x76, 0xc9, 0x2f, 0x81, 0xf5, 0x24, 0xb3, 0x3c, 0x57, 0x37, 0x64, 0x76,
	0x9a, 0x03, 0xaf, 0xce, 0x09, 0xf6, 0xdb, 0xdd, 0xe7, 0x2c, 0xb9, 0x08, 0xa9, 0xeb, 0x01, 0xf1,
	0x87, 0xd1, 0xd8, 0x85, 0x82, 0x36, 0x82, 0xf5, 0xe9, 0x50, 0x6f, 0xb2, 0xd2, 0x8f, 0xe1, 0x9d,
	0x6f, 0x89, 0xec, 0xb2, 0xac, 0x32, 0x81, 0x59, 0xda, 0x0f, 0x50, 0x3c, 0x14, 0xb3, 0x38, 0x85,
	0xfd, 0x12, 0x32, 0x51, 0x50, 0x01, 0x5f, 0x20, 0x49, 0x89, 0xd7, 0x1e, 0x14, 0x28, 0x5e, 0x88,
	0x11, 0x7d, 0xb6, 0x3b, 0x27, 0x48, 0xc2, 0xb7, 0x86, 0xa8, 0x39, 0x69, 0xce, 0x8f, 0xf9, 0x62,
	0xf9, 0x1e, 0xb3, 0x2b, 0x49, 0x12, 0x7e, 0xd6, 0xaa, 0x50, 0x0c, 0xa7, 0x6f, 0x81, 0x7e, 0xfc,
	0xa5, 0xc0, 0x5a, 0x04, 0x3b, 0xf3, 0x88, 0x2f, 0x16, 0x5d, 0xe2, 0x4a, 0xfa, 0x19, 0x0a, 0x54,
	0x02, 0xac, 0x60, 0xe8, 0x85, 0x4b, 0xa9, 0x50, 0xfb, 0x62, 0x4e, 0x4d, 0xe3, 0x5b, 0xf5, 0xf1,
	0xa9, 0x39, 0xf4, 0x88, 0x99, 0xa7, 0x93, 0xa2, 0xb6, 0x07, 0xf9, 0x98, 0x1d, 0x6d, 0x42, 0xe9,
	0xac, 0x51, 0x37, 0xf7, 0x9b, 0x27, 0x67, 0xa7, 0x56, 0xf3, 0xc7, 0x46, 0xdd, 0xba, 0x38, 0x3d,
	0x6f, 0xd4, 0x0f, 0x4f, 0x8e, 0x4f, 0xea, 0x47, 0x6b, 0x6f, 0x21, 0x80, 0xf4, 0xa1, 0x59, 0xdf,
	0x6f, 0xd6, 0xd7, 0x94, 0xda, 0x9f, 0x69, 0xc8, 0xca, 0xb9, 0x43, 0xbf, 0xc2, 0xea, 0x24, 0xe3,
	0xd0, 0xa7, 0xff, 0x97, 0xe0, 0x14, 0x31, 0x4a, 0x9f, 0x2d, 0x06, 0x0e, 0x47, 0x5b, 0x2b, 0xfe,
	0xf6, 0xf7, 0x3f, 0x7f, 0x2c, 0x15, 0xd0, 0xea, 0xe4, 0xb7, 0x05, 0xfd, 0xae, 0x40, 0x21, 0xce,
	0x05, 0xb4, 0x3d, 0xeb, 0xda, 0x44, 0x7a, 0x96, 0xf4, 0x45, 0xe1, 0x51, 0x1e, 0x9b, 0x22, 0x0f,
	0x55, 0x7b, 0x39, 0x99, 0xc7, 0x2e, 0x13, 0xe0, 0x5d, 0xa5, 0x8a, 0x6e, 0x01, 0x1e, 0xd9, 0x81,
	0x3e, 0x99, 0x75, 0xfb, 0x13, 0x06, 0x95, 0xe6, 0x0d, 0xac, 0xb6, 0x21, 0x22, 0xbf, 0x46, 0xaf,
	0x78, 0xe4, 0x7b, 0x3e, 0x28, 0x5f, 0x49, 0xd8, 0xc8, 0xa8, 0xa2, 0x11, 0xe4, 0x63, 0x6c, 0x43,
	0x33, 0xfb, 0x9b, 0x44, 0xca, 0x85, 0xc3, 0x6b, 0xb1, 0x07, 0xd8, 0x1d, 0xb3, 0xe8, 0x41, 0x81,
	0x7c, 0x8c, 0x99, 0xb3, 0xe3, 0x27, 0x11, 0x78, 0x7e, 0x7c, 0x5d, 0xc4, 0xaf, 0xd4, 0x36, 0x44,
	0xf9, 0x11, 0x42, 0x8f, 0xb5, 0xc1, 0xa8, 0x8e, 0x1e, 0x13, 0x1a, 0x41, 0x3e, 0xc6, 0xcc, 0xd9,
	0xf9, 0x24, 0x11, 0x78, 0xe1, 0x7e, 0x54, 0x13, 0x9e, 0xc3, 0xa8, 0x8e, 0x0e, 0xbe, 0xf9, 0xe9,
	0xeb, 0x8e, 0x13, 0x74, 0x07, 0x2d, 0xbd, 0x4d, 0xfb, 0x06, 0xe9, 0x39, 0x98, 0xdd, 0x31, 0x23,
	0xbc, 0x73, 0x1b, 0x7b, 0x8e, 0x3c, 0x4f, 0xff, 0x37, 0xed, 0xc9, 0x73, 0x2b, 0x2d, 0x56, 0xcf,
	0xe7, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x3e, 0x19, 0x58, 0x1c, 0x61, 0x09, 0x00, 0x00,
}
